--- # This playbook installs apache on connected hosts and hosts a static web page
- hosts: jenkinsgroup
  user: ansibleuser
  become: yes
  connection: ssh
  tasks:
   - name: Installing Httpd
     action: yum name=httpd state=installed
   - name: Copy index.html to /var/www/html
     action: copy src=./index.html dest=/var/www/html
   - name: Enabling Firewall in ansible node
     shell: |
      firewall-cmd --add-service=http --permanent
      firewall-cmd --reload
   - name: Starting Apache Server
     action: service name=httpd state=started
  gather_facts: yes
